version: "3.9"
services:
 rest-bcb:
  image: "allan.oliveira/rest-bcb:1.0.0-SNAPSHOT"
  ports:
   - "8081:8081"
 client-api:
  image: "allan.oliveira/client-api:1.0.0-SNAPSHOT"
  ports:
   - "8082:8082"
  environment:
   - QUARKUS_REST_CLIENT_BCB_PROXY_URL=http://rest-bcb:8081